name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Set up release dependencies
      run: |
        cargo install --locked cargo-zigbuild
    - name: Build
      run: cargo build
    - name: Release Binaries
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{secrets.GH_PAT}}
